# Generated by Django 4.2.20 on 2025-04-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='symbol',
            field=models.CharField(default='BTC', max_length=10),
            preserve_default=False,
        ),
    ]
