# Generated by Django 4.2.20 on 2025-04-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_portfolio_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=10)),
                ('current_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('market_cap', models.DecimalField(decimal_places=10, max_digits=30)),
                ('price_change_percentage_24h', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.URLField()),
            ],
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='coin_id',
            new_name='coin_name',
        ),
    ]
