# Generated by Django 4.2.20 on 2025-04-24 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
